In [1]:
import json

def read_jsonl(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            yield json.loads(line)

for data in read_jsonl('sampleds4.jsonl'):
    print(data)

{'id': 'seed_task_0', 'type': 'general', 'question': 'What position does Shyam Sundar currently hold at USEReady?', 'context': {'sentences': [['Shyam Sundar\n♂phone+91-9080765574 /envel⌢pemailshyamsundar.2022@gmail.com /linkedinshyamsundar007 /githubShyam-Sundar-7♂laptopPortfolio\nExperience\nUSEReady April 2024 – Present\nMachine Learning Engineer Intern Bengaluru, Karnataka\n•Developed a custom RAG chatbot that leverages multi-query generation andkeyword extraction , integrates with\nAzure ,AWS , and local storage , and features an interactive Streamlit user interface. /github/video\n•Engineered a Retrieval-Augmented Generation incorporating human feedback by labelling responses, fine-tuning the\ncross-encoder , and integrating it into a Streamlit interface for enhanced user interaction.', '•Incorporated FAISS for refined recommendation processes. PeopleCare Insurance Prediction /github |Python, Jupyter, Azure Cloud, Flask, Docker October 2023\n•Expanded PeopleCare into vehicle insurance with a predictive model for effective customer targeting . •Thorough analysis of customer behaviour and data cleaning for accurate predictive modelling.', '•Engineered a path prediction algorithm using a sequence-to-sequence model with an attention mechanism . Federated Learning on Multiclass classification |Python, Deep Learning, Jupyter Notebook June 2022 - July 2022\n•Utilized the CIFAR dataset for training, involving 20 client nodes with training activities based on the VGG-19 model . •Central global model collected weight updates from six randomly selected client models, averaging the contributions, and\ndisseminated the updated global model to all participating clients.']], 'title': [['placeholder_title', 'placeholder_title', 'placeholder_title']]}, 'oracle_context': 'Shyam Sundar\n♂phone+91-9080765574 /envel⌢pemailshyamsundar.2022@gmail.com /linkedinshyamsundar007 /githubShyam-Sundar-7♂laptopPortfolio\nExperience\nUSEReady April 2024 – Present\nMachine Learning Engineer Intern Bengaluru, Karnataka\n•Developed a custom RAG chatbot that leverages multi-query generation andkeyword extraction , integrates with\nAzure ,AWS , and local storage , and features an interactive Streamlit user interface. /github/video\n•Engineered a Retrieval-Augmented Generation incorporating human feedback by labelling responses, fine-tuning the\ncross-encoder , and integrating it into a Streamlit interface for enhanced user interaction.', 'cot_answer': 'Step 1: Identify the key elements in the question. The question is asking for the current position of Shyam Sundar at USEReady.\n\nStep 2: Look for the relevant information in the context. The context provides information about Shyam Sundar\'s experience at USEReady.\n\nStep 3: Extract the relevant information from the context. The context states: ##begin_quote##"USEReady April 2024 – Present Machine Learning Engineer Intern Bengaluru, Karnataka"##end_quote##. This indicates that Shyam Sundar is currently working as a Machine Learning Engineer Intern at USEReady.\n\nStep 4: Formulate the answer based on the extracted information. \n\n<ANSWER>: Shyam Sundar currently holds the position of Machine Learning Engineer Intern at USEReady.', 'instruction': '<DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /envel⌢pemailshyamsundar.2022@gmail.com /linkedinshyamsundar007 /githubShyam-Sundar-7♂laptopPortfolio\nExperience\nUSEReady April 2024 – Present\nMachine Learning Engineer Intern Bengaluru, Karnataka\n•Developed a custom RAG chatbot that leverages multi-query generation andkeyword extraction , integrates with\nAzure ,AWS , and local storage , and features an interactive Streamlit user interface. /github/video\n•Engineered a Retrieval-Augmented Generation incorporating human feedback by labelling responses, fine-tuning the\ncross-encoder , and integrating it into a Streamlit interface for enhanced user interaction.</DOCUMENT>\n<DOCUMENT>•Incorporated FAISS for refined recommendation processes. PeopleCare Insurance Prediction /github |Python, Jupyter, Azure Cloud, Flask, Docker October 2023\n•Expanded PeopleCare into vehicle insurance with a predictive model for effective customer targeting . •Thorough analysis of customer behaviour and data cleaning for accurate predictive modelling.</DOCUMENT>\n<DOCUMENT>•Engineered a path prediction algorithm using a sequence-to-sequence model with an attention mechanism . Federated Learning on Multiclass classification |Python, Deep Learning, Jupyter Notebook June 2022 - July 2022\n•Utilized the CIFAR dataset for training, involving 20 client nodes with training activities based on the VGG-19 model . •Central global model collected weight updates from six randomly selected client models, averaging the contributions, and\ndisseminated the updated global model to all participating clients.</DOCUMENT>\nWhat position does Shyam Sundar currently hold at USEReady?'}
{'id': 'seed_task_1', 'type': 'general', 'question': 'What kind of chatbot did Shyam Sundar develop during his internship at USEReady?', 'context': {'sentences': [['•Executed model deployment via Flask andDocker for scalability. Machine Failure Prediction /github |Azure Machine Learning September 2023\n•Conducted an extensive investigation of a Milling machine to enhance operational reliability. •Conceived 97% recall rate for predicting machine failures using logistic regression and SMOTE .', '•Effected a commendable accuracy rate of 78% upon completing the training process, demonstrating the effectiveness of the\nfederated learning approach in preserving data security and privacy while maintaining model performance. Education\nDefence Institute of Advanced Technology Pune, IN\nM.Tech in Modelling and Simulation, GPA: 7.95 May 2023\nNational Institute of Technology Tiruchirappalli, IN\nB.Tech in Chemical Engineering, GPA: 7.65 May 2021\nTechnical Skills\nLanguages : Python, C/C++, SQL (Postgres), Matlab, Latex\nFrameworks Tools : Pytorch, Tensorflow, Flask, Pytorch Lightning,Tableau, Power Bi, Azure, Git, Jupyter, Docker\nCertifications\n•Certified Associate Data Analyst\n•SQL [Advanced] - Hackerank\n•Management Consulting Mentorship\n•Generative AI at SAP•ML for Business professionals using No-Code AI tools\n•Python [Basic] - Hackerank\n•Software Engineer Intern -Hackerank\n•Generative AI Fundamentals - Databricks\nPublications\nSuspicious Event Detection of Cargo Vessels Based on AIS Data at ICDMAI,2023', 'Shyam Sundar\n♂phone+91-9080765574 /envel⌢pemailshyamsundar.2022@gmail.com /linkedinshyamsundar007 /githubShyam-Sundar-7♂laptopPortfolio\nExperience\nUSEReady April 2024 – Present\nMachine Learning Engineer Intern Bengaluru, Karnataka\n•Developed a custom RAG chatbot that leverages multi-query generation andkeyword extraction , integrates with\nAzure ,AWS , and local storage , and features an interactive Streamlit user interface. /github/video\n•Engineered a Retrieval-Augmented Generation incorporating human feedback by labelling responses, fine-tuning the\ncross-encoder , and integrating it into a Streamlit interface for enhanced user interaction.']], 'title': [['placeholder_title', 'placeholder_title', 'placeholder_title']]}, 'oracle_context': 'Shyam Sundar\n♂phone+91-9080765574 /envel⌢pemailshyamsundar.2022@gmail.com /linkedinshyamsundar007 /githubShyam-Sundar-7♂laptopPortfolio\nExperience\nUSEReady April 2024 – Present\nMachine Learning Engineer Intern Bengaluru, Karnataka\n•Developed a custom RAG chatbot that leverages multi-query generation andkeyword extraction , integrates with\nAzure ,AWS , and local storage , and features an interactive Streamlit user interface. /github/video\n•Engineered a Retrieval-Augmented Generation incorporating human feedback by labelling responses, fine-tuning the\ncross-encoder , and integrating it into a Streamlit interface for enhanced user interaction.', 'cot_answer': 'Step 1: Identify the key elements in the question. The question is asking about the type of chatbot that Shyam Sundar developed during his internship at USEReady.\n\nStep 2: Look for relevant information in the context. The context provides information about Shyam Sundar\'s experience at USEReady, including the development of a chatbot.\n\nStep 3: Extract the relevant information from the context. The context states: ##begin_quote##"Developed a custom RAG chatbot that leverages multi-query generation and keyword extraction , integrates with Azure ,AWS , and local storage , and features an interactive Streamlit user interface."##end_quote##\n\nStep 4: Formulate the answer. Based on the information from the context, Shyam Sundar developed a custom RAG chatbot during his internship at USEReady.\n\n<ANSWER>: Shyam Sundar developed a custom RAG chatbot during his internship at USEReady.', 'instruction': '<DOCUMENT>•Executed model deployment via Flask andDocker for scalability. Machine Failure Prediction /github |Azure Machine Learning September 2023\n•Conducted an extensive investigation of a Milling machine to enhance operational reliability. •Conceived 97% recall rate for predicting machine failures using logistic regression and SMOTE .</DOCUMENT>\n<DOCUMENT>•Effected a commendable accuracy rate of 78% upon completing the training process, demonstrating the effectiveness of the\nfederated learning approach in preserving data security and privacy while maintaining model performance. Education\nDefence Institute of Advanced Technology Pune, IN\nM.Tech in Modelling and Simulation, GPA: 7.95 May 2023\nNational Institute of Technology Tiruchirappalli, IN\nB.Tech in Chemical Engineering, GPA: 7.65 May 2021\nTechnical Skills\nLanguages : Python, C/C++, SQL (Postgres), Matlab, Latex\nFrameworks Tools : Pytorch, Tensorflow, Flask, Pytorch Lightning,Tableau, Power Bi, Azure, Git, Jupyter, Docker\nCertifications\n•Certified Associate Data Analyst\n•SQL [Advanced] - Hackerank\n•Management Consulting Mentorship\n•Generative AI at SAP•ML for Business professionals using No-Code AI tools\n•Python [Basic] - Hackerank\n•Software Engineer Intern -Hackerank\n•Generative AI Fundamentals - Databricks\nPublications\nSuspicious Event Detection of Cargo Vessels Based on AIS Data at ICDMAI,2023</DOCUMENT>\n<DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /envel⌢pemailshyamsundar.2022@gmail.com /linkedinshyamsundar007 /githubShyam-Sundar-7♂laptopPortfolio\nExperience\nUSEReady April 2024 – Present\nMachine Learning Engineer Intern Bengaluru, Karnataka\n•Developed a custom RAG chatbot that leverages multi-query generation andkeyword extraction , integrates with\nAzure ,AWS , and local storage , and features an interactive Streamlit user interface. /github/video\n•Engineered a Retrieval-Augmented Generation incorporating human feedback by labelling responses, fine-tuning the\ncross-encoder , and integrating it into a Streamlit interface for enhanced user interaction.</DOCUMENT>\nWhat kind of chatbot did Shyam Sundar develop during his internship at USEReady?'}
{'id': 'seed_task_2', 'type': 'general', 'question': 'What technology was used to develop the LLM-Powered Coupon Recommender?', 'context': {'sentences': [['/github\nProjects\nLLM-Powered Coupon Recommender /github/video |Python, Streamlit, Langchain, OpenAI November 2023\n•Developed a QA system for e-commerce with personalized coupon recommendations using OpenAI’s LLMs . •Streamlined user interactions through a Streamlit interface and Langchain for real-world scenario simulations.', '•Managed in Azure Designer for comprehensive data analysis and predictive modeling. Data Driven Model for Anomaly Detection and Path Prediction |Python, Deep Learning July 2022 - April 2023\n•Investigated and improved AIS for cargo vessel anomaly detection and path prediction. •Formulated a statistical method for robust anomaly detection .', '•Effected a commendable accuracy rate of 78% upon completing the training process, demonstrating the effectiveness of the\nfederated learning approach in preserving data security and privacy while maintaining model performance. Education\nDefence Institute of Advanced Technology Pune, IN\nM.Tech in Modelling and Simulation, GPA: 7.95 May 2023\nNational Institute of Technology Tiruchirappalli, IN\nB.Tech in Chemical Engineering, GPA: 7.65 May 2021\nTechnical Skills\nLanguages : Python, C/C++, SQL (Postgres), Matlab, Latex\nFrameworks Tools : Pytorch, Tensorflow, Flask, Pytorch Lightning,Tableau, Power Bi, Azure, Git, Jupyter, Docker\nCertifications\n•Certified Associate Data Analyst\n•SQL [Advanced] - Hackerank\n•Management Consulting Mentorship\n•Generative AI at SAP•ML for Business professionals using No-Code AI tools\n•Python [Basic] - Hackerank\n•Software Engineer Intern -Hackerank\n•Generative AI Fundamentals - Databricks\nPublications\nSuspicious Event Detection of Cargo Vessels Based on AIS Data at ICDMAI,2023']], 'title': [['placeholder_title', 'placeholder_title', 'placeholder_title']]}, 'oracle_context': '/github\nProjects\nLLM-Powered Coupon Recommender /github/video |Python, Streamlit, Langchain, OpenAI November 2023\n•Developed a QA system for e-commerce with personalized coupon recommendations using OpenAI’s LLMs . •Streamlined user interactions through a Streamlit interface and Langchain for real-world scenario simulations.', 'cot_answer': 'Step 1: Identify the key elements in the question. The question is asking about the technology used to develop the LLM-Powered Coupon Recommender.\n\nStep 2: Look for the relevant information in the context. The context mentions the LLM-Powered Coupon Recommender and lists the technologies used in its development.\n\nStep 3: Extract the relevant information from the context. The context states: ##begin_quote##"LLM-Powered Coupon Recommender /github/video |Python, Streamlit, Langchain, OpenAI November 2023"##end_quote## and ##begin_quote##"Developed a QA system for e-commerce with personalized coupon recommendations using OpenAI’s LLMs . Streamlined user interactions through a Streamlit interface and Langchain for real-world scenario simulations."##end_quote##\n\nStep 4: Formulate the answer based on the extracted information. The technologies used to develop the LLM-Powered Coupon Recommender are Python, Streamlit, Langchain, and OpenAI.\n\n<ANSWER>: The LLM-Powered Coupon Recommender was developed using Python, Streamlit, Langchain, and OpenAI.', 'instruction': '<DOCUMENT>/github\nProjects\nLLM-Powered Coupon Recommender /github/video |Python, Streamlit, Langchain, OpenAI November 2023\n•Developed a QA system for e-commerce with personalized coupon recommendations using OpenAI’s LLMs . •Streamlined user interactions through a Streamlit interface and Langchain for real-world scenario simulations.</DOCUMENT>\n<DOCUMENT>•Managed in Azure Designer for comprehensive data analysis and predictive modeling. Data Driven Model for Anomaly Detection and Path Prediction |Python, Deep Learning July 2022 - April 2023\n•Investigated and improved AIS for cargo vessel anomaly detection and path prediction. •Formulated a statistical method for robust anomaly detection .</DOCUMENT>\n<DOCUMENT>•Effected a commendable accuracy rate of 78% upon completing the training process, demonstrating the effectiveness of the\nfederated learning approach in preserving data security and privacy while maintaining model performance. Education\nDefence Institute of Advanced Technology Pune, IN\nM.Tech in Modelling and Simulation, GPA: 7.95 May 2023\nNational Institute of Technology Tiruchirappalli, IN\nB.Tech in Chemical Engineering, GPA: 7.65 May 2021\nTechnical Skills\nLanguages : Python, C/C++, SQL (Postgres), Matlab, Latex\nFrameworks Tools : Pytorch, Tensorflow, Flask, Pytorch Lightning,Tableau, Power Bi, Azure, Git, Jupyter, Docker\nCertifications\n•Certified Associate Data Analyst\n•SQL [Advanced] - Hackerank\n•Management Consulting Mentorship\n•Generative AI at SAP•ML for Business professionals using No-Code AI tools\n•Python [Basic] - Hackerank\n•Software Engineer Intern -Hackerank\n•Generative AI Fundamentals - Databricks\nPublications\nSuspicious Event Detection of Cargo Vessels Based on AIS Data at ICDMAI,2023</DOCUMENT>\nWhat technology was used to develop the LLM-Powered Coupon Recommender?'}

In [2]:
import pandas as pd
import json

def read_jsonl(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            yield json.loads(line)

data = list(read_jsonl('sampleds4.jsonl'))
df = pd.json_normalize(data)

print(df)

              id     type                                           question  \
0    seed_task_0  general  What position does Shyam Sundar currently hold...
1    seed_task_1  general  What kind of chatbot did Shyam Sundar develop ...
2    seed_task_2  general  What technology was used to develop the LLM-Po...
3    seed_task_3  general  What was the main function of the LLM-Powered ...
4    seed_task_4  general  What tools were used for the project "PeopleCa...
5    seed_task_5  general  What was the new expansion introduced in Peopl...
6    seed_task_6  general  What was the accuracy of the hate speech detec...
7    seed_task_7  general  Which model was used to achieve an 80% predict...
8    seed_task_8  general  What method was used for model deployment for ...
9    seed_task_9  general  What was the recall rate achieved for predicti...
10  seed_task_10  general  What tool was used to manage comprehensive dat...
11  seed_task_11  general  What method did the user formulate for robust ...
12  seed_task_12  general  What type of model was used in the path predic...
13  seed_task_13  general  How many client nodes were involved in the CIF...
14  seed_task_14  general  Which educational institute did this individua...
15  seed_task_15  general  What certifications does this individual hold ...

                                       oracle_context  \
0   Shyam Sundar\n♂phone+91-9080765574 /envel⌢pema...
1   Shyam Sundar\n♂phone+91-9080765574 /envel⌢pema...
2   /github\nProjects\nLLM-Powered Coupon Recommen...
3   /github\nProjects\nLLM-Powered Coupon Recommen...
4   •Incorporated FAISS for refined recommendation...
5   •Incorporated FAISS for refined recommendation...
6   •Achieved 80% prediction accuracy using LightG...
7   •Achieved 80% prediction accuracy using LightG...
8   •Executed model deployment via Flask andDocker...
9   •Executed model deployment via Flask andDocker...
10  •Managed in Azure Designer for comprehensive d...
11  •Managed in Azure Designer for comprehensive d...
12  •Engineered a path prediction algorithm using ...
13  •Engineered a path prediction algorithm using ...
14  •Effected a commendable accuracy rate of 78% u...
15  •Effected a commendable accuracy rate of 78% u...

                                           cot_answer  \
0   Step 1: Identify the key elements in the quest...
1   Step 1: Identify the key elements in the quest...
2   Step 1: Identify the key elements in the quest...
3   Step 1: Identify the key elements in the quest...
4   Step 1: Identify the relevant information in t...
5   Step 1: Identify the key elements in the quest...
6   To answer the question, we need to find the in...
7   Step 1: Identify the relevant information in t...
8   Step 1: Understand the question. The question ...
9   To answer the question, we need to find the in...
10  Step 1: Identify the key elements in the quest...
11  Step 1: Identify the relevant information in t...
12  Step 1: Identify the relevant information in t...
13  To answer the question, we need to identify th...
14  To answer the question, we need to find the in...
15  To answer the question, we need to look at the...

                                          instruction  \
0   <DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /...
1   <DOCUMENT>•Executed model deployment via Flask...
2   <DOCUMENT>/github\nProjects\nLLM-Powered Coupo...
3   <DOCUMENT>•Executed model deployment via Flask...
4   <DOCUMENT>•Engineered a path prediction algori...
5   <DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /...
6   <DOCUMENT>•Achieved 80% prediction accuracy us...
7   <DOCUMENT>•Managed in Azure Designer for compr...
8   <DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /...
9   <DOCUMENT>•Achieved 80% prediction accuracy us...
10  <DOCUMENT>•Engineered a path prediction algori...
11  <DOCUMENT>•Managed in Azure Designer for compr...
12  <DOCUMENT>•Achieved 80% prediction accuracy us...
13  <DOCUMENT>•Incorporated FAISS for refined reco...
14  <DOCUMENT>•Incorporated FAISS for refined reco...
15  <DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /...

                                    context.sentences  \
0   [[Shyam Sundar\n♂phone+91-9080765574 /envel⌢pe...
1   [[•Executed model deployment via Flask andDock...
2   [[/github\nProjects\nLLM-Powered Coupon Recomm...
3   [[•Executed model deployment via Flask andDock...
4   [[•Engineered a path prediction algorithm usin...
5   [[Shyam Sundar\n♂phone+91-9080765574 /envel⌢pe...
6   [[•Achieved 80% prediction accuracy using Ligh...
7   [[•Managed in Azure Designer for comprehensive...
8   [[Shyam Sundar\n♂phone+91-9080765574 /envel⌢pe...
9   [[•Achieved 80% prediction accuracy using Ligh...
10  [[•Engineered a path prediction algorithm usin...
11  [[•Managed in Azure Designer for comprehensive...
12  [[•Achieved 80% prediction accuracy using Ligh...
13  [[•Incorporated FAISS for refined recommendati...
14  [[•Incorporated FAISS for refined recommendati...
15  [[Shyam Sundar\n♂phone+91-9080765574 /envel⌢pe...

                                        context.title
0   [[placeholder_title, placeholder_title, placeh...
1   [[placeholder_title, placeholder_title, placeh...
2   [[placeholder_title, placeholder_title, placeh...
3   [[placeholder_title, placeholder_title, placeh...
4   [[placeholder_title, placeholder_title, placeh...
5   [[placeholder_title, placeholder_title, placeh...
6   [[placeholder_title, placeholder_title, placeh...
7   [[placeholder_title, placeholder_title, placeh...
8   [[placeholder_title, placeholder_title, placeh...
9   [[placeholder_title, placeholder_title, placeh...
10  [[placeholder_title, placeholder_title, placeh...
11  [[placeholder_title, placeholder_title, placeh...
12  [[placeholder_title, placeholder_title, placeh...
13  [[placeholder_title, placeholder_title, placeh...
14  [[placeholder_title, placeholder_title, placeh...
15  [[placeholder_title, placeholder_title, placeh...

In [3]:
df.head()

,id,type,question,oracle_context,cot_answer,instruction,context.sentences,context.title
0,seed_task_0,general,What position does Shyam Sundar currently hold...,Shyam Sundar\n♂phone+91-9080765574 /envel⌢pema...,Step 1: Identify the key elements in the quest...,<DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /...,[[Shyam Sundar\n♂phone+91-9080765574 /envel⌢pe...,"[[placeholder_title, placeholder_title, placeh..."
1,seed_task_1,general,What kind of chatbot did Shyam Sundar develop ...,Shyam Sundar\n♂phone+91-9080765574 /envel⌢pema...,Step 1: Identify the key elements in the quest...,<DOCUMENT>•Executed model deployment via Flask...,[[•Executed model deployment via Flask andDock...,"[[placeholder_title, placeholder_title, placeh..."
2,seed_task_2,general,What technology was used to develop the LLM-Po...,/github\nProjects\nLLM-Powered Coupon Recommen...,Step 1: Identify the key elements in the quest...,<DOCUMENT>/github\nProjects\nLLM-Powered Coupo...,[[/github\nProjects\nLLM-Powered Coupon Recomm...,"[[placeholder_title, placeholder_title, placeh..."
3,seed_task_3,general,What was the main function of the LLM-Powered ...,/github\nProjects\nLLM-Powered Coupon Recommen...,Step 1: Identify the key elements in the quest...,<DOCUMENT>•Executed model deployment via Flask...,[[•Executed model deployment via Flask andDock...,"[[placeholder_title, placeholder_title, placeh..."
4,seed_task_4,general,"What tools were used for the project ""PeopleCa...",•Incorporated FAISS for refined recommendation...,Step 1: Identify the relevant information in t...,<DOCUMENT>•Engineered a path prediction algori...,[[•Engineered a path prediction algorithm usin...,"[[placeholder_title, placeholder_title, placeh..."

In [4]:
df.columns

Index(['id', 'type', 'question', 'oracle_context', 'cot_answer', 'instruction',
       'context.sentences', 'context.title'],
      dtype='object')

In [5]:
df[['instruction','cot_answer','context.sentences', 'context.title']].head()

,instruction,cot_answer,context.sentences,context.title
0,<DOCUMENT>Shyam Sundar\n♂phone+91-9080765574 /...,Step 1: Identify the key elements in the quest...,[[Shyam Sundar\n♂phone+91-9080765574 /envel⌢pe...,"[[placeholder_title, placeholder_title, placeh..."
1,<DOCUMENT>•Executed model deployment via Flask...,Step 1: Identify the key elements in the quest...,[[•Executed model deployment via Flask andDock...,"[[placeholder_title, placeholder_title, placeh..."
2,<DOCUMENT>/github\nProjects\nLLM-Powered Coupo...,Step 1: Identify the key elements in the quest...,[[/github\nProjects\nLLM-Powered Coupon Recomm...,"[[placeholder_title, placeholder_title, placeh..."
3,<DOCUMENT>•Executed model deployment via Flask...,Step 1: Identify the key elements in the quest...,[[•Executed model deployment via Flask andDock...,"[[placeholder_title, placeholder_title, placeh..."
4,<DOCUMENT>•Engineered a path prediction algori...,Step 1: Identify the relevant information in t...,[[•Engineered a path prediction algorithm usin...,"[[placeholder_title, placeholder_title, placeh..."

In [7]:
data = list(read_jsonl('output.completion.jsonl'))
df1 = pd.json_normalize(data)

df1.head()

,prompt,completion
0,What position does Shyam Sundar currently hold...,Step 1: Identify the key elements in the quest...
1,What kind of chatbot did Shyam Sundar develop ...,Step 1: Identify the key elements in the quest...
2,What technology was used to develop the LLM-Po...,Step 1: Identify the key elements in the quest...
3,What was the main function of the LLM-Powered ...,Step 1: Identify the key elements in the quest...
4,"What tools were used for the project ""PeopleCa...",Step 1: Identify the relevant information in t...

In [8]:
df1.to_csv('output.completion.csv', index=False)

In [8]:
df2=pd.read_csv("output.completion.csv")

In [9]:
df2.head()

,prompt,completion,answer
0,What position does Shyam Sundar currently hold...,Step 1: Identify the key elements in the quest...,Shyam Sundar currently holds the position of ...
1,What kind of chatbot did Shyam Sundar develop ...,Step 1: Identify the key elements in the quest...,Shyam Sundar developed a custom RAG chatbot d...
2,What technology was used to develop the LLM-Po...,Step 1: Identify the key elements in the quest...,The LLM-Powered Coupon Recommender was develo...
3,What was the main function of the LLM-Powered ...,Step 1: Identify the key elements in the quest...,The main function of the LLM-Powered Coupon R...
4,"What tools were used for the project ""PeopleCa...",Step 1: Identify the relevant information in t...,"The tools used for the project ""PeopleCare In..."

In [10]:
df2.drop(columns=['completion'],inplace=True)
df2.to_csv("raft-custom-dataset.csv", index=False)